"""Criando Tabela Users

Revision ID: f5d8e60957cb
Revises: 
Create Date: 2025-09-15 00:58:34.313852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d8e60957cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='api'
    )
    op.create_index(op.f('ix_api_usuarios_email'), 'usuarios', ['email'], unique=True, schema='api')
    op.create_index(op.f('ix_api_usuarios_id'), 'usuarios', ['id'], unique=False, schema='api')
    op.create_index(op.f('ix_api_usuarios_nome'), 'usuarios', ['nome'], unique=False, schema='api')
    op.create_index(op.f('ix_api_usuarios_username'), 'usuarios', ['username'], unique=False, schema='api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usuarios_username'), table_name='usuarios', schema='api')
    op.drop_index(op.f('ix_api_usuarios_nome'), table_name='usuarios', schema='api')
    op.drop_index(op.f('ix_api_usuarios_id'), table_name='usuarios', schema='api')
    op.drop_index(op.f('ix_api_usuarios_email'), table_name='usuarios', schema='api')
    op.drop_table('usuarios', schema='api')
    # ### end Alembic commands ###
